Adding the ability to make funnel shaped tubes
DrLex0/print3D-customizable-sieve pull request #1
Opened 2022-05-17 19:28 UTC by beettlle

Adding the ability to create tapers on the tubes.  This is to make it easier to make sieve funnels for ground coffee.

2022-05-18 09:56 UTC, DrLex0 commented
It's a good idea, but it will need some refinements due to the kludgy way I trimmed the grid to the outer shape. Currently it starts sticking out when using a taper value considerably larger than 1.
I suggest I'll merge this after you incorporated my suggested change, and then I'll see how I can update the trimming routine to produce better results. Of course, you can also have a shot at it if you wish 😉

2022-05-18 17:16 UTC, DrLex0 requested changes

2022-05-18 17:16 UTC, DrLex0 commented on sieve.scad
> +taper=1; //[1::3]
Can you change this to:
```suggestion
taper=1; //[1:.01:3]
```
Otherwise the customizer interface in OpenSCAD will only allow values 1, 2, and 3.

2022-05-18 18:33 UTC, beettlle commented on sieve.scad
> +taper=1; //[1::3]
Thank you. Interestingly, to me the stuff that "escapes" the cylinder is helpful as I'm doing this to make a sieve for ground coffee.  The protrusions let it sit better on the portafilter.  One person's bug is another person's feature :).  But I agree, this should happen on command and not by chance.

I'll make the change later on today.

2022-05-18 18:59 UTC, DrLex0 commented on sieve.scad
> +taper=1; //[1::3]
I have tried some things, and the best way to fix it seems sticking to a straight cylinder for the lower part of the model and only start tapering above the top Z coordinate of the filter mesh. Not sure if that would help in your case.
![new](https://user-images.githubusercontent.com/16401844/169133543-48b63190-f927-45b7-a9af-4d5dc5be2896.png)

2022-05-19 11:04 UTC, DrLex0 approved these changes

2022-05-19 11:04 UTC, merged